### ISSUE TITLE
Gettting "cannot load compass" after upgrading to Sass 3.3.5 / Compass 0.12.5

### ISSUE THREAD

**Issue by DerZyklop** [gruntjs/grunt-contrib-sass#114]
This is quite the same like #103 but with newer versions.

I hotfixed it by doing 
`sudo gem uninstall sass`
`sudo gem uninstall compass`
and
`sudo gem install compass --version 0.12.4`
which will also install a compatible sass-version as already mentioned by @Cyberlane in #103.

**Comment by felipsmartins** [comment]
it worked for me, thanks @DerZyklop
