### ISSUE TITLE
file to import not found or unreadable: "compass"

### ISSUE THREAD

**Issue by patrickbjohnson** [gruntjs/grunt-contrib-sass#128]
Trying to include compass in a project I'm using via grunt. Adhering to the method listed in the docs, but anytime I add <code>@import "compass";</code> to my main.scss file I'm given the following error: 

<code>Warning: /Users/.../styles/main.scss:4: error: file to import not found or unreadable: "compass"</code>

The Scss file has nothing more than the generated styles from the yeoman webapp generation and the <code>@import "compass";</code> included above that. Not sure what is or isn't happening properly but would love some guidance as I'm new to grunt. 

If it helps, here's the sass section of my gruntfile.js: 

```
sass: {
            options: {   // i've also tested including the compass option here, but results in the same error. 
                includePaths: [
                    'bower_components'
                ]
            },
            dist: {
                options: {
                    compass: true
                },
                files: [{
                    expand: true,
                    cwd: '<%= config.app %>/styles',
                    src: ['*.scss'],
                    dest: '.tmp/styles',
                    ext: '.css'
                }]
            },
            server: {
                files: [{
                    expand: true,
                    cwd: '<%= config.app %>/styles',
                    src: ['*.scss'],
                    dest: '.tmp/styles',
                    ext: '.css'
                }]
            }
        },
```

**Comment by iMomen** [comment]
With the current version of " grunt-contrib-sass " you have to set compass option to true in your sass task i.e: 

> sass: {
>            dis: {
>                options: {
>                    style: 'compressed',
>                    compass: true
>                },
>                files: {
>                    'stylesheets/screen.css' : 'sass/screen.scss'
>                }
>          }
>        },
