### ISSUE TITLE
You need to have Ruby and Sass installed and in your PATH for this task to work.

### ISSUE THREAD

**Issue by thadallender** [gruntjs/grunt-contrib-sass#131]
Ruby and Sass are both installed on my Ubuntu server, but I'm still getting this error message when executing grunt sass via PHP shell_exec() to compile Bourbon:

`which ruby: /usr/bin/ruby`
`ruby -v: ruby 1.9.3p484`
`which sass: /usr/local/bin/sass`
`sass -v: Sass 3.3.9 (Maptastic Maple)`

Here is what I know:
1. When I run this command via command line, all sass (including Bourbon) compiles fine with no warnings.
2. When it's executed via shell_exec(), it creates this warning and doesn't compile any sass.
3. When I remove Bourbon, execute via shell_exec(), it compiles fine with no warnings.

This confirms that:
1. All dependencies are installed
2. grunt-contrib-sass can compile custom sass over command line
3. grunt-contrib-sass can compile Bourbon over command line
4. grunt-contrib-sass can compile custom sass when using shell_exec()
5. grunt-contrib-sass fails to compile Bourbon when using shell_exec()

The warning message itself doesn't seem accurate, but, I'm unable to debug any further to figure out what might be wrong. At this point, I'm not sure where the problem lies.

**Comment by patrickdlee** [comment]
I was up against this same issue on an Ubuntu server and used this alternate "solution"...

sudo ln -s /usr/local/bin/sass /bin/sass

Not very satisfying, but it works without any Gruntfile.js changes.
