### ISSUE TITLE
Question: What does "dist" stand for?

### ISSUE THREAD

**Issue by jeloi** [gruntjs/grunt-contrib-sass#133]
Just curious.

**Comment by roppa** [comment]
I think it means Distribution, as the files are or can be spread around different directories. @Jeloi you are correct, the docs do not define the abbreviation. @sindresorhus if the web is to be open for everyone then all terms should be defined.

**Comment by jmk2142** [comment]
Glad someone else asked it. I was wondering the same thing. Seeing it everywhere but always took it for granted. Now it makes a lot more sense.

**Comment by Drockio** [comment]
Thanks for asking Jeloi. I was wondering too.
