### ISSUE TITLE
You need to have Ruby and Sass installed and in your PATH for this task to work.

### ISSUE THREAD

**Issue by Ranosi** [gruntjs/grunt-contrib-sass#165]
I've seen other threads here about it but still could not solve my problem. Sass is installed correctly, but when I try to compile the file I keep having this error:

Running "sass:dist" (sass) task
Warning:
You need to have Ruby and Sass installed and in your PATH for this task to work.

Any help!?

**Comment by marcker** [comment]
(Linux)

When I installed with `sudo gem install sass` this not create the `sass` alias, but sass.ruby 2.1, so I did:

```sh
which sass.ruby2.1 # /usr/bin/sass.ruby2.1
cd /usr/bin
sudo ln -s  /usr/bin/sass.ruby2.1 sass
```
