### ISSUE TITLE
Cannot compile a partial

### ISSUE THREAD

**Issue by glebm** [gruntjs/grunt-contrib-sass#180]
I am developing a Sass library that consists only of partials. However, it seems impossible to use grunt-contrib-sass to compile non-partials. 

```js
dist: {
  files: {
    'dist/css/library.css': 'scss/_library.scss' // <- not compiled
  }
}
```

The reasons I want  only partials in the library:

1. Sass `--watch` outputs all non-prefixed files as separate CSS files. E.g. if a user copies my library  directly into the project, then imports it into their `scss/main.scss`, and runs `sass --watch`:

```console
$ sass --watch scss:public  
      write public/main.css
      write public/library.css
```

2. Compass [copies](https://github.com/Compass/compass/issues/1757#issuecomment-52563160) all non-partials in the libraries into the project when the library is added:

```console
$ compass compile
 modified config.rb
        ...
    write stylesheets/screen.css
directory stylesheets/library
    write stylesheets/library/library.css
```

---

Sister ticket: https://github.com/sindresorhus/grunt-sass/issues/176

**Comment by tbremer** [comment]
SASS inherently does not compile partials (assuming you use the _partial.s(ac)ss convention). 

This library (obviously) follows that same convention. You only need to send this module your non partial files, and your output files.

**Comment by glebm** [comment]
Sass can compile partials:

```console
$ sass tmp/_test.sass
```

**Comment by sindresorhus** [comment]
The problem is that this task don't know whether a glob or specific file where used as grunt does the globbing and just passes down a list of files. Just import your partials into a normal Sass file and compile that instead.

**Comment by glebm** [comment]
Yes, this would require a new option to override the behaviour (e.g. `compilePartials: true`). I'll see if I can PR this soon.

**Comment by tbremer** [comment]
Sass will compile anything you pass it, but the idea of a partial is that you import it into another file. 

If you were to use `--update` or `--watch` and pass your input and output directory then you'd see That Sass does not compile partials, it compiles the files that import said partials.
