### ISSUE TITLE
Can't interpolate variables with @import directive

### ISSUE THREAD

**Issue by javierlopezdeancos** [gruntjs/grunt-contrib-sass#181]
I can't interpolate a variable with @import directive as I read in the sass documentation
[import documentation for sass](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import)

This way is very usefull and works, 
[An example](http://sassmeister.com/gist/dda5f4344df703632805)

What is the problem???

A example of code with I try to reproduce the example documentation with grunt-contrib-sass pluging and not work.

    $path_bower_components: unquote("../../../bower_components");
    @import url("#{$path_bower_components}/MyDependencieProject/src/styles/MyDependencieImportFile");

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow.

Make sure you're on the latest Sass version.

**Comment by javierlopezdeancos** [comment]
Ok but my gem sass version is

$ sass -v
Sass 3.4.11

and I try with the same structure and files to compile with gem by command terminal and works, with this grunt  pluging not work properly.
