### ISSUE TITLE
Style option is not taking effect

### ISSUE THREAD

**Issue by mkenter** [gruntjs/grunt-contrib-sass#183]
My style option is being passed over using the following code:

```
sass: {
	dev: {
		option: {
			style: 'compressed'
		},
		files: {
			'<%= dirs.cssDir %>/main.css': '<%= dirs.scssDir %>/main.scss'
		}
	}
}
```

**Comment by sindresorhus** [comment]
Are you sure you're using `grunt-contrib-sass` and not `grunt-sass`? Paste in the output of running `grunt sass --verbose`.

**Comment by mkenter** [comment]
So it's optionS not option. Long day. Sorry!
