### ISSUE TITLE
JS exception since 0.9.0

### ISSUE THREAD

**Issue by yaycmyk** [gruntjs/grunt-contrib-sass#186]
> /Users/esj/Documents/VC/tictacs/jarvis/node_modules/grunt-contrib-sass/node_modules/cross-spawn/node_modules/lru-cache/lib/lru-cache.js:132
});

Loading "sass.js" tasks...ERROR
> SyntaxError: Unexpected token )

**Comment by sindresorhus** [comment]
That is coming from https://github.com/IndigoUnited/node-cross-spawn/issues/new Open an issue over there.
