### ISSUE TITLE
Cannot complete because of missing lockfile

### ISSUE THREAD

**Issue by Wortex17** [gruntjs/grunt-contrib-sass#188]
I cannot run the following task
```
"sass": {
            "Client/SASS": {
                files: {
                    'stack/public/stylesheets/main.css': 'client/sass/main.scss'
                }
            }
        }
```
because of the following error

```
Errno::ENOENT: No such file or directory - F:/ExChat/.sass-cache/6ec841a708d858b2ff612058238cdaca7001470f/main.scssc20150209-7160-1eot8ca.lock
  Use --trace for backtrace.
Warning: Exited with error code 1 Use --force to continue.
```

should it really be a reason to halt/err if a lockfile is missing? It isn't there but the directory is, which leads me to the conclusion that it's probably unlocked twice.

(Windows 8.0, x64)

**Comment by sindresorhus** [comment]
That error is coming from Sass and not this plugin. This plugin is only a thin wrapper upon the Sass binary.
