### ISSUE TITLE
Warning: Exited with error code 100

### ISSUE THREAD

**Issue by soundasleep** [gruntjs/grunt-contrib-sass#189]
On Windows x64 I am getting this warning repeatedly but very intermittently, but it doesn't seem to cause any problems. It looks like it's an issue with Sass holding onto file descriptors perhaps - I don't know what "100" means and --debug/--verbose provides no better debug information, but does sometimes reduce the frequency of the errors, maybe because of the slowness of printing extra debug information to console.

```
Running "sass:dist" (sass) task
Warning: Exited with error code 100 Use --force to continue.
```

To reproduce: run `grunt sass sass sass sass sass` - it's likely one of these targets will return 100, causing the grunt process to stop.

Hacky suggestion: change 

```
if (code > 0) {
``` 

to 

```
if (code > 0 && code !== 100) {
```

* ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
* Sass 3.2.19 (Media Mark)
* grunt-contrib-sass 0.9.2

**Comment by sindresorhus** [comment]
:palm_tree: Not going to add a workaround without knowing why it happens. This issue is better opened on Sass itself as it seems there some issue on Windows. :palm_tree:
