### ISSUE TITLE
Complex folder structure with a lot of css files

### ISSUE THREAD

**Issue by Trigu** [gruntjs/grunt-contrib-sass#190]
#### Hi everyone,

I have a lot of css files in my project with a very complex structure so I had to replicate the structure of the folders containing css files at the root of the project.
So every time I save a scss file, grunt has to check each 160+ lines of config I gave him.
Is there a way to optimize this this configuration? Maybe an option to tell contrib-sass to compile the scss file with the same structure he's in?

Here is a simplified example of my code :

```javascript
   sass: {
      dist: {
        options: {
          style: 'expanded',
          sourcemap: 'none',
          trace: true,
        },
        files: {
          './css/laptop.css': './scss/css/laptop.scss',
         ....
         ... (160 more lines)
         ....
          './css/player.css': './scss/css/player.scss'
        }
      }
    },
```

#### Thanks!

**Comment by tbremer** [comment]
I, also, have a fairly complicated workflow with lots of included files and symlinked directories.

We use a globbing pattern and the `files.expand: true` option exposed by Grunt.

```javascript
sass: {
    options: {
        sourcemap: 'none',
        trace: true,
        style: 'nested',
    },
    dist: {
        files: [{
            expand: true,
            src: ['<%= configs.minimatch %>', '!**/node_modules/**'],
            dest: '<%= configs.compilePaths.production %>',
            ext: '.css'
        }]
    }
}
```

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
