### ISSUE TITLE
'file.css': [...] not working

### ISSUE THREAD

**Issue by monolithed** [gruntjs/grunt-contrib-sass#191]
```js
files: {
	'index.css': [
		'file1.scss',
		'file2.scss'
	]
}
```

```js
files: [
	{
		src  : ['file1.scss', 'file2.scss'],
		dest: 'index.css'
	}
]
```

Included only the first file!

**Comment by sindresorhus** [comment]
That's not supported. Use grunt-contrib-concat if you need to concat files, or even better, just use the Sass @import thingy.

**Comment by monolithed** [comment]
@sindresorhus, hm. But it's standard Grunt 

For example:

Your solution:
```sass
@import '../../../../node_modules/normalize/index.sass'
```

My solution:
```
src  : [
     'index.scss', 
     require.resolve('normalize/index.sass'),
     // ... and more other polyfills and components
],
```

It's more comfortable for me. 
Why cut the standard grunt features?

**Comment by sindresorhus** [comment]
It's not standard. It's up to each task if it makes sense. And here it doesn't make sense.
