### ISSUE TITLE
Sass globbing doesn't work after updating

### ISSUE THREAD

**Issue by justnorris** [gruntjs/grunt-contrib-sass#192]
This just in. Today I decided to run `npm update` ( It's been a year or so )

~~~
Running "sass:default" (sass) task
Error: File to import not found or unreadable: modules/button/button.sass.
       Load paths:
        /path/to/my/webroot/
         Sass::Globbing::Importer
        on line 1 of assets/sass/modules/*/**
        from line 37 of assets/sass/app.sass
  Use --trace for backtrace.
Warning: Exited with error code 65 Use --force to continue.
~~~

/modules/button/button.sass file is there. Everything is exactly as it was before I updated, except now Sass globbing doesn't work. I also tried updating my gems - didn't help.

**Comment by tbremer** [comment]
This is an error in sass-globbing...

https://github.com/chriseppstein/sass-globbing/issues/19
