### ISSUE TITLE
Feature Request: Non-Verbose logging

### ISSUE THREAD

**Issue by tbremer** [gruntjs/grunt-contrib-sass#193]
I'd like an option that isn't `--verbose` to be able to see the files that are being compiled.

I have a rather large set of SCSS files that do not all compile to one style sheet, when I compile the process takes a bit of time, I'd like an option (such as: `logCompiles`, `smartChatter`) that would print the same output from a [verbose log](https://github.com/gruntjs/grunt-contrib-sass/blob/73546de3cb077feaef5c0ba8a2307c1b2d23c432/tasks/sass.js#L104), but avoiding the chatter from other Grunt Tasks.

Thoughts?

The change would be pretty insignificant and low impacting:

![grunt-contrib-smartchatter](https://cloud.githubusercontent.com/assets/2998575/6406431/4e3b3c2c-bdf6-11e4-9366-7b9453d4bcbf.png)

**Comment by sindresorhus** [comment]
Sounds like a feature request for `grunt`. Being able to trigger verbose mode on a task level.

https://github.com/gruntjs/grunt/issues/new

**Comment by tbremer** [comment]
Will file, thanks!
