### ISSUE TITLE
Compile Files Doesn't Run

### ISSUE THREAD

**Issue by ozgrozer** [gruntjs/grunt-contrib-sass#194]
Hi,

I'm new in grunt and sorry for if this is a bad question.
I want to compile scss files in a directory but it doesn't run.

This is my code look like;
```javascript
sass:{
	dist:{
		options:{
			style:"compressed",
			sourcemap:"none",
			noCache:true
		},
		files:[{
			expand:true,
			cwd:"css/development",
			src:["css/development/*.scss"],
			dest:"css/production",
			ext:".css"
		}]
	}
}
```

What is wrong with these codes?

**Comment by tbremer** [comment]
Try removing `cwd: "css/development",`

Assuming your paths are correct are you saying all your of your source files are located at: `css/development/css/development/*.scss'

**Comment by ozgrozer** [comment]
Thank you for helpful comment. It works now.

Now it's look like
```javascript
files:[{
	expand:true,
	cwd:"css/development",
	src:["*.scss"],
	dest:"css/production",
	ext:".min.css"
}]
```
