### ISSUE TITLE
Question: Banner option removed?

### ISSUE THREAD

**Issue by jesusjjf** [gruntjs/grunt-contrib-sass#200]
I use the banner option on a regular basis. 
Is there a specific reason why it was removed?
Thanks!

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-sass/commit/12bb4c8fe6a544d33fe1dc09504bba47a6aeffb5

**Comment by cowgill** [comment]
I couldn't find grunt-contrib-contrib but found [grunt-contrib](https://github.com/gruntjs/grunt-contrib) which has been deprecated.

I ended up using [Grunt Banner](https://github.com/mattstyles/grunt-banner) which is a sufficient alternative.

**Comment by julmot** [comment]
:+1:

**Comment by ERROPiX** [comment]
@sindresorhus why grunt-contrib-uglify is still using it and grunt-contrib-sass isn't? uglifyjs also have sourcemaps
