### ISSUE TITLE
Option to use tabs instead of spaces

### ISSUE THREAD

**Issue by cowgill** [gruntjs/grunt-contrib-sass#206]
When outputting the expanded css, this would be very nice to have. 

**Current output (two spaces)**
```
body {
  margin: 0;
}
```

**Desired output (one tab)**
```
body {
    margin: 0;
}
```

**Comment by sindresorhus** [comment]
Nah. Can easily be achieved with a separate task, and other than you, I doubt anyone would need this as most compile Sass=>CSS for production.
