### ISSUE TITLE
cwd is not taken into account when computing dest

### ISSUE THREAD

**Issue by JVerstry** [gruntjs/grunt-contrib-sass#207]
The documentation says that this configuration is ok:

      sass: {
        dist: {
          files: [{
            expand: true,
            cwd: 'styles',
            src: ['*.scss'],
            dest: '../public',
            ext: '.css'
          }]
        }
      }

but if a project is in c:\project\myproject\Gruntfile.js, then this module will generate the css files in:

    c:\project\public

rather than in:

    c:\project\myproject\public

This issue was originally reported in a stackoverflow question: http://stackoverflow.com/questions/31791572/grunt-sass-contrib-does-not-generate-css-files-in-target-directory

**Comment by sindresorhus** [comment]
Only `src` is relative to `cwd`, not `dest`. http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by JVerstry** [comment]
Ok, but then the documentation should be updated, because it is misleading...
