### ISSUE TITLE
Date/time not updated on sass targets

### ISSUE THREAD

**Issue by FranceBaril** [gruntjs/grunt-contrib-sass#212]
My client is on Windows and we have this issus only on his computer (latest ruby/node.js/grunt/compass and sass). The sass process runs and creates the target file, but the date/time isn't updated correctly on some of the files. 

![screen shot 2015-09-14 at 14 38 28](https://cloud.githubusercontent.com/assets/12036551/9862612/bee6179a-5aee-11e5-914a-d04bc3f39375.png)

In the attached image, you see 2 targets, the first one gets updated (content has latest changes and if we delete the old file, a new one gets created), but the date/time on the file system is wrong (keeps the date from the original target). The second one gets updated correctly with the latest date/time.

I can't provide more details and I realize that this is a weird item that happens on a single computer so far. I'm submitting it in case others have the same issue.

**Comment by sindresorhus** [comment]
This should be opened on https://github.com/sass/sass/issues. This plugin just calls the Sass binary with the provided options.
