### ISSUE TITLE
Variable as a key for path.

### ISSUE THREAD

**Issue by artfaal** [gruntjs/grunt-contrib-sass#217]
Hi! Weird behavior. 
```
var sourseScssFolder = 'src/scss/*.scss';
var destCssFile = 'src/packed.css';
sass: {
            dist: {
                options: {
                    style: 'nested'
                },
                files: {
                    // Key don't wanna load from variable
                    destCssFile: sourseScssFolder,
                }
            }
        },
```
After this compiler create file "dest File", instead read from var. How fix this?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by artfaal** [comment]
http://stackoverflow.com/questions/34510954/variable-as-a-key-for-path-in-gruntjs
