### ISSUE TITLE
not compiling files version 1.0.0

### ISSUE THREAD

**Issue by douglasdeodato** [gruntjs/grunt-contrib-sass#223]
hello guys i am getting this error when i am running grunt sass:

my file is called _main.scss, if i use _main.scss does not appear error but the compiled files are empty, if i remove the _  (slash) and use just main.scss i get this error bellow.

grunt sass
Running "sass:dev" (sass) task
Errno::ENOENT: No such file or directory @ rb_sysopen - undefined
  Use --trace for backtrace.
Warning: Exited with error code 1 Use --force to continue.

Aborted due to warnings.

Execution Time (2016-04-18 07:56:54 UTC)
loading tasks  655ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 41%
sass:dev       940ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 59%
Total 1.6s

my gruntfile.js

 grunt.initConfig({
    config: {
      pkg: pkg,
      appName: pkg.name,
      app: '.',
      distFolder: 'dist',
      serverPort: 9000,
      serverHost: '0.0.0.0',
      livereloadPort: grunt.option('livereload') ? 35729 : false,
      jsSources: 'app/**/*.js',
      lessMain: 'less/main.less',
      sassMain: 'scss/main.scss'
    }

watch: {
  sass: {
        files: ['scss/**/*.scss'],
        tasks: ['scss:dev'],
        options: {
          livereload: '<%= config.livereloadPort %>'
        }
}

  sass: {
      dev: {
        options: {
          style: 'expanded'
        },
        files: {
          'css/sass_main.development.css': '<%= config.sassMain %>'
        }
      },
      dist: {
        options: {
         style: 'compressed'
        },
        files: {
          '<%= config.distFolder %>/css/sass_main.min.css':
          '<%= config.sassMain %>'
        }
      }
    },

  grunt.registerTask('build', [
    'clean',
    'jshint',
    'sass:dist',
    'less:dist',
    'copy:dist',
    'useminPrepare',
    'concat:generated',
    'uglify:generated',
    'filerev',
    'usemin',
    'ngdocs'
  ]);

someone can help?  thank you.

**Comment by douglasdeodato** [comment]
solved but i still have a question why my _main.scss where i have all the imports cant be with slash _ ? i changed it for just main.scss and worked well, but my all other files has _ . thank you

**Comment by sindresorhus** [comment]
That's clearly explained in the readme: https://github.com/gruntjs/grunt-contrib-sass#sass-task
