### ISSUE TITLE
I am not able to run gulp command on my Git bash Here. Working on Windows 7(32 bit)

### ISSUE THREAD

**Issue by niksbhandari003** [gruntjs/grunt-contrib-sass#225]
Gives Error After Server Started Port: as below. Someone please Help me out

[17:51:42] Finished 'default' after 6.98 μs
[17:51:42] Server started http://localhost:8080
[17:51:42] LiveReload started on port 35729
[17:51:42] { [Error: You need to have Ruby and Compass installed and in your system PATH for this task to work.]
  message: 'You need to have Ruby and Compass installed and in your system PATH for this task to work.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function: bound ] } }

**Comment by sindresorhus** [comment]
The error message is pretty clear:

> You need to have Ruby and Compass installed and in your system PATH for this task to work.

More in the readme.

**Comment by niksbhandari003** [comment]
Dear Sir ,
I have tried command set PATH=C:\Ruby23\bin;%PATH%
and Compass create path/to/Desktop/Responsive.

Git Bash Here still gives Same Error

On Tue, Jun 28, 2016 at 6:07 PM, Sindre Sorhus <notifications@github.com>
wrote:

> The error message is pretty clear:
>
> You need to have Ruby and Compass installed and in your system PATH for
> this task to work.
>
> More in the readme.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gruntjs/grunt-contrib-sass/issues/225#issuecomment-229036297>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATGG7ZWxmoJzjbgfDRmNDBqwaz68F13eks5qQRWDgaJpZM4JADCz>
> .
>



-- 
Thanks and Regards,

     Mr. Nikhil J. Bhandari
     Shri Swami Samarth Trust, Dindori, Nashik
     [image: Nikhil Bhandari Facebook Profile]
<https://www.facebook.com/nikhil.bhandari.712>
<https://twitter.com/niksbhandari003> [image: Nikhil Bhandari: Linked
Profile] <https://in.linkedin.com/pub/nikhil-bhandari/4a/64a/432>
<https://plus.google.com/+nikhilbhandari003>
     8087216351
