### ISSUE TITLE
compiled to an empty css file

### ISSUE THREAD

**Issue by ghost** [gruntjs/grunt-contrib-sass#23]
Hello,

I am sorry to bring the problem here cause I think it's not an issue, I just can't find the answer to the problem. I've been goggling and through forums for days now. Kind of desparated.

I am trying to compile scss file using the grunt-contrib-sass plugin (with grunt v0.4.0). The compiled result is an empty css file, but if through Sass, already installed on my pc, it works fine. Below are the base.scss, Gruntfile.js and package.json files.

base.scss

```
$color: #000;

header{
color: $color;  
}
```

Gruntfile.js

```
module.exports = function(grunt) {
// Project configuration.
grunt.initConfig({
    // Metadata.
    pkg: grunt.file.readJSON('package.json'),       
    sass: {
        dist: {
            options: { style: "expanded", trace: true },
            files: { "base.css": "base.scss" }
        }       
    }
});

grunt.loadNpmTasks('grunt-contrib-sass');

// Default task.
grunt.registerTask("default", [""]);
grunt.registerTask("sass--",["sass"]);
};
```

package.json

```
{
"name": "my_grunt",
"version": "1.0.0",
"description": "New to Grunt",
"main": "index.js",
"scripts": {
    "test": "test"
},
"repository": {
    "type": "git",
    "url": "none"

},
"keywords": [
        "none"
],
"author": "none",
"license": "BSD",
"devDependencies": {
        "grunt-contrib-sass": "~0.2.2"
}
}
```

Result:

Either I run the sass command "grunt sass" or "grunt sass--", the result is just an empty css file without any errors.

Your help is greatly appreciated

Niusaul

**Comment by jebaraj2016** [comment]
Hi ,
I couldn't execute my grunt files 

# grunt -v 

  Gruntfile.js
     63 |                NODE_ENV : 'unit-test',
                                               ^ [W108] Strings must use doublequote.
     64 |                DEST     : 'temp'
                                          ^ [W108] Strings must use doublequote.
   core/logger/index.js
     55 |function formatter(args){
                  ^ [W003] 'formatter' was used before it was defined.
     56 |    return moment().format('MM/DD/YY hh:mm:ss a') + ' - ' + args.level + ': ' + args.message;
                                                         ^ [W108] Strings must use doublequote.
     56 |    return moment().format('MM/DD/YY hh:mm:ss a') + ' - ' + args.level + ': ' + args.message;
                                                                  ^ [W108] Strings must use doublequote.
     56 |    return moment().format('MM/DD/YY hh:mm:ss a') + ' - ' + args.level + ': ' + args.message;
                                                                                      ^ [W108] Strings must use doublequote.
   core/server/api/applications.js
     81 |        var application = new Application();
                                       ^ [W117] 'Application' is not defined.
      1 |var mongoose = require("mongoose"),
             ^ [W098] 'mongoose' is defined but never used.
      5 |    dataProvider = require("../models"),
             ^ [W098] 'dataProvider' is defined but never used.
   core/server/api/droptickets.js
     17 |        for (var property in options) {
                 ^ [W089] The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.
     42 |                })
                           ^ [W033] Missing semicolon.
      1 |var mongoose = require("mongoose"),
             ^ [W098] 'mongoose' is defined but never used.
      5 |    dataProvider = require("../models"),
             ^ [W098] 'dataProvider' is defined but never used.
   core/server/api/settings.js
      1 |var mongoose = require("mongoose"),
             ^ [W098] 'mongoose' is defined but never used.
   core/server/api/taxonomy.js
      1 |var mongoose = require("mongoose"),
             ^ [W098] 'mongoose' is defined but never used.
   core/server/api/users.js
     29 |        var User = db.model('User');
                                           ^ [W108] Strings must use doublequote.
     31 |        var Business = db.model('Business');
                                                   ^ [W108] Strings must use doublequote.
     64 |        var promise = when.promise(function (resolve, reject) {
                                                               ^ [W098] 'reject' is defined but never used.
     62 |    getMe: function (options) {
                              ^ [W098] 'options' is defined but never used.
     73 |        var User = db.model('User');
                                           ^ [W108] Strings must use doublequote.
      1 |var mongoose = require("mongoose"),
             ^ [W098] 'mongoose' is defined but never used.
      5 |    dataProvider = require("../models"),
             ^ [W098] 'dataProvider' is defined but never used.
   core/server/index.js
     10 |        res.header('Access-Control-Allow-Origin', '*');
                                                         ^ [W108] Strings must use doublequote.
     10 |        res.header('Access-Control-Allow-Origin', '*');
                                                              ^ [W108] Strings must use doublequote.
     11 |        res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, apikey, Authorization');
                                                          ^ [W108] Strings must use doublequote.
     11 |        res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, apikey, Authorization');
                                                                                                                                   ^ [W108] Strings must use doublequote.
     13 |    }).options('*', function(req, res, next){
                           ^ [W108] Strings must use doublequote.
     13 |    }).options('*', function(req, res, next){
                                                ^ [W098] 'next' is defined but never used.
     15 |    })
               ^ [W033] Missing semicolon.
     39 |        var server = app.listen(config.get("server:port"));
                     ^ [W098] 'server' is defined but never used.
     42 |    })
               ^ [W033] Missing semicolon.
     63 |    server.close();
             ^ [W117] 'server' is not defined.
   core/server/middleware/index.js
     26 |            var UserModel = mongoose_instance.getDatabase().model('User');
                                                                                 ^ [W108] Strings must use doublequote.
     41 |            var UserModel = mongoose_instance.getDatabase().model('User');
                                                                                 ^ [W108] Strings must use doublequote.
     50 |                    return done(null, user, { scope: 'all' });
                                                                   ^ [W108] Strings must use doublequote.
     60 |        passport.authenticate("local", function (err, user, info) {
                                                                     ^ [W098] 'info' is defined but never used.
     75 |        passport.authenticate("bearer", function (err, user, info) {
                                                                      ^ [W098] 'info' is defined but never used.
     98 |        var ApplicationModel = mongoose_instance.getDatabase().model('Application');
                                                                                           ^ [W108] Strings must use doublequote.
      2 |    dataProvider = require("../models"),
             ^ [W098] 'dataProvider' is defined but never used.
      5 |    User = require("../models").User,
             ^ [W098] 'User' is defined but never used.
   core/server/models/application.js
     21 |    user_id: {type: Schema.ObjectId, ref: 'User', default: null},
                                                         ^ [W108] Strings must use doublequote.
     27 |    this.model('Application').findOne({ apikey: appData.apikey }, function (err, application) {
                                     ^ [W108] Strings must use doublequote.
     39 |}
          ^ [W033] Missing semicolon.
     42 |    var model = this.model('Application');
                                                 ^ [W108] Strings must use doublequote.
     43 |    var application = new model();
                                   ^ [W055] A constructor name should start with an uppercase letter.
     51 |}
          ^ [W033] Missing semicolon.
     65 |    var model = this.model('Application');
                                                 ^ [W108] Strings must use doublequote.
     66 |    var application = new model(record);
                                   ^ [W055] A constructor name should start with an uppercase letter.
     77 |}
          ^ [W033] Missing semicolon.
     80 |    var model = this.model('Application');
                                                 ^ [W108] Strings must use doublequote.
     81 |    var applicationModel = new model();
                                        ^ [W055] A constructor name should start with an uppercase letter.
    105 |}
          ^ [W033] Missing semicolon.
    108 |    this.model('Application').findOne({ _id: helper.mongoObjectId(data.id) }, function (err, application) {
                                     ^ [W108] Strings must use doublequote.
    120 |}
          ^ [W033] Missing semicolon.
    124 |    var model = this.model('Application');
                                                 ^ [W108] Strings must use doublequote.
    125 |    var application = new model();
                                   ^ [W055] A constructor name should start with an uppercase letter.
    153 |}
          ^ [W033] Missing semicolon.
      9 |    Application,
             ^ [W098] 'Application' is defined but never used.
     11 |    ApplicationModel,
             ^ [W098] 'ApplicationModel' is defined but never used.
    155 |function getApplicationByApiKey(appData, callback) {
                  ^ [W098] 'getApplicationByApiKey' is defined but never used.
   core/server/models/authentication.js
     14 |    user_id: {type: Schema.ObjectId, ref: 'User'},
                                                         ^ [W108] Strings must use doublequote.
     21 |}
          ^ [W033] Missing semicolon.
      1 |var _ = require("lodash"),
             ^ [W098] '_' is defined but never used.
      2 |    jwt = require("jwt-simple"),
             ^ [W098] 'jwt' is defined but never used.
      3 |    mongo = require("../../db/mongo"),
             ^ [W098] 'mongo' is defined but never used.
      5 |    logger = require("../../logger"),
             ^ [W098] 'logger' is defined but never used.
      6 |    errors = require("../helpers").errors,
             ^ [W098] 'errors' is defined but never used.
      7 |    helper = require("../helpers"),
             ^ [W098] 'helper' is defined but never used.
      8 |    filteredAttributes = ["_id", "password"],
             ^ [W098] 'filteredAttributes' is defined but never used.
   core/server/models/business.js
     25 |  this.model('Business').findOne({ bid: data.bid}, function (err, business) {
                                ^ [W108] Strings must use doublequote.
     37 |}
          ^ [W033] Missing semicolon.
     42 |}
          ^ [W033] Missing semicolon.
      2 |    jwt = require("jwt-simple"),
             ^ [W098] 'jwt' is defined but never used.
      3 |    mongo = require("../../db/mongo"),
             ^ [W098] 'mongo' is defined but never used.
      7 |    helper = require("../helpers"),
             ^ [W098] 'helper' is defined but never used.
   core/server/models/index.js
      1 |var mongoose = require('mongoose'),
                                          ^ [W108] Strings must use doublequote.
      3 |    ApplicationSchema = require('./application').ApplicationSchema,
                                                        ^ [W108] Strings must use doublequote.
      4 |    UserSchema = require('./user').UserSchema,
                                          ^ [W108] Strings must use doublequote.
      5 |    AuthenticationSchema = require('./authentication').AuthenticationSchema,
                                                              ^ [W108] Strings must use doublequote.
      6 |    BusinessSchema = require('./business').BusinessSchema,
                                                  ^ [W108] Strings must use doublequote.
      7 |    SettingSchema = require('./setting').SettingSchema,
                                                ^ [W108] Strings must use doublequote.
      8 |    TaxonomySchema = require('./taxonomy').TaxonomySchema,
                                                  ^ [W108] Strings must use doublequote.
     13 |    db.model('Application', ApplicationSchema);
                                   ^ [W108] Strings must use doublequote.
     13 |    db.model('Application', ApplicationSchema);
                                                      ^ [W030] Expected an assignment or function call and instead saw an expression.
     14 |    db.model('User', UserSchema);
                            ^ [W108] Strings must use doublequote.
     15 |    db.model('Authentication', AuthenticationSchema);
                                      ^ [W108] Strings must use doublequote.
     16 |    db.model('Business', BusinessSchema);
                                ^ [W108] Strings must use doublequote.
     17 |    db.model('Setting', SettingSchema);
                               ^ [W108] Strings must use doublequote.
     18 |    db.model('Taxonomy', TaxonomySchema);
                                ^ [W108] Strings must use doublequote.
     19 |}
          ^ [W033] Missing semicolon.
     12 |    db = mongoose_instance.getDatabase(),
             ^ [W117] 'db' is not defined.
     13 |    db.model('Application', ApplicationSchema);
             ^ [W117] 'db' is not defined.
     14 |    db.model('User', UserSchema);
             ^ [W117] 'db' is not defined.
     15 |    db.model('Authentication', AuthenticationSchema);
             ^ [W117] 'db' is not defined.
     16 |    db.model('Business', BusinessSchema);
             ^ [W117] 'db' is not defined.
     17 |    db.model('Setting', SettingSchema);
             ^ [W117] 'db' is not defined.
     18 |    db.model('Taxonomy', TaxonomySchema);
             ^ [W117] 'db' is not defined.
      1 |var mongoose = require('mongoose'),
             ^ [W098] 'mongoose' is defined but never used.
   core/server/models/setting.js
     24 |    this.model('Setting').findOne({ bid: data.bid }, function (err, setting) {
                                 ^ [W108] Strings must use doublequote.
     36 |}
          ^ [W033] Missing semicolon.
      3 |    mongo = require("../../db/mongo"),
             ^ [W098] 'mongo' is defined but never used.
      6 |    Setting,
             ^ [W098] 'Setting' is defined but never used.
      8 |    SettingModel,
             ^ [W098] 'SettingModel' is defined but never used.
   core/server/models/taxonomy.js
     16 |}, {collection: 'taxonomies'});
                                     ^ [W108] Strings must use doublequote.
     19 |    this.model('Taxonomy').findOne({ bid: data.bid }, function (err, setting) {
                                  ^ [W108] Strings must use doublequote.
     31 |}
          ^ [W033] Missing semicolon.
      3 |    mongo = require("../../db/mongo"),
             ^ [W098] 'mongo' is defined but never used.
      6 |    Taxonomy,
             ^ [W098] 'Taxonomy' is defined but never used.
      8 |    TaxonomyModel,
             ^ [W098] 'TaxonomyModel' is defined but never used.
   core/server/models/user.js
     30 |UserSchema.pre('save', function(next) {
                              ^ [W108] Strings must use doublequote.
     32 |    if (!user.isModified('password')) return next();
                                            ^ [W108] Strings must use doublequote.
     32 |    if (!user.isModified('password')) return next();
                                               ^ [W116] Expected '{' and instead saw 'return'.
     49 |    var model = this.model('User');
                                          ^ [W108] Strings must use doublequote.
     50 |    var user = new model(data);
                            ^ [W055] A constructor name should start with an uppercase letter.
     52 |    user.save(function (err) {
                                 ^ [W098] 'err' is defined but never used.
     56 |}
          ^ [W033] Missing semicolon.
     59 |    var Authentication = mongoose_instance.getDatabase().model('Authentication', AuthenticationSchema);
                                                                                        ^ [W108] Strings must use doublequote.
     60 |    this.model('User').findOne({ email: data.email }, function (err, user) {
                              ^ [W108] Strings must use doublequote.
     99 |}
          ^ [W033] Missing semicolon.
    102 |    var Authentication = mongoose_instance.getDatabase().model('Authentication', AuthenticationSchema);
                                                                                        ^ [W108] Strings must use doublequote.
    126 |}
          ^ [W033] Missing semicolon.
    129 |    var Authentication = mongoose_instance.getDatabase().model('Authentication', AuthenticationSchema);
                                                                                        ^ [W108] Strings must use doublequote.
    130 |    var userModel = this.model('User');
                                              ^ [W108] Strings must use doublequote.
    153 |}
          ^ [W033] Missing semicolon.
    156 |    this.model('User').findOne({ email: data.email }, function (err, user) {
                              ^ [W108] Strings must use doublequote.
    170 |}
          ^ [W033] Missing semicolon.
    173 |    this.model('User').findOne({ _id: helper.mongoObjectId(data.id) }, function (err, user) {
                              ^ [W108] Strings must use doublequote.
    186 |}
          ^ [W033] Missing semicolon.
     36 |            return cb(errors.SERVER_ERROR);
                            ^ [W117] 'cb' is not defined.
     40 |                return cb(errors.SERVER_ERROR);
                                ^ [W117] 'cb' is not defined.
      5 |    mongo = require("../../db/mongo"),
             ^ [W098] 'mongo' is defined but never used.
   core/server/routes/index.js
      9 |    User = require("../models").User,
             ^ [W098] 'User' is defined but never used.
     10 |    errors = require("../helpers").errors,
             ^ [W098] 'errors' is defined but never used.
   core/server/routes/settings.js
      2 |    middleware = require("../middleware"),
             ^ [W098] 'middleware' is defined but never used.
   core/server/routes/taxonomy.js
      2 |    middleware = require("../middleware"),
             ^ [W098] 'middleware' is defined but never used.
   test/functional/api/payments_test.js
    166 |                    service_fee: .50
                                             ^ [W008] A leading decimal point can be confused with a dot: '.50'.
    191 |                    service_fee: .50,
                                             ^ [W008] A leading decimal point can be confused with a dot: '.50'.
    192 |                    tip_rate: .30
                                          ^ [W008] A leading decimal point can be confused with a dot: '.30'.
    217 |                    service_fee: .50,
                                             ^ [W008] A leading decimal point can be confused with a dot: '.50'.
    218 |                    tip_rate: .30,
                                          ^ [W008] A leading decimal point can be confused with a dot: '.30'.

>> 140 errors in 39 files
Warning: Task "jshint:files" failed. Use --force to continue.

Aborted due to warnings.
root@helpdesk:/var/www/html/dev/api# cd ..
root@helpdesk:/var/www/html/dev# cd dashboard/
root@helpdesk:/var/www/html/dev/dashboard# grunt
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

Please help out this problem.
