### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ghost** [gruntjs/grunt-contrib-sass#24]
Hello,

I have error when running same code on a window environment. It works fine on a MAC. Here are my files:

Gruntfile.js

module.exports = function(grunt) {
            // Project configuration.
            grunt.initConfig({
                // Metadata.
                    pkg: grunt.file.readJSON('package.json'),  
                    sass: {
                         dist: {
                             options: { style: "expanded", trace: true },
                             files: { "build/css/illicoweb.css": "src/scss/illicoweb.scss" }
                     }  
                    }
             });

```
        grunt.loadNpmTasks('grunt-contrib-sass');

        // Default task.
        grunt.registerTask("default", [""]);
        grunt.registerTask("sass--",["sass"]);
```

};

package.json

{
    "name": "illico",
    "version": "1.0.0",
    "description": "illicoweb on Grunt",
    "devDependencies": {
        "grunt-contrib-watch": "~0.3.1",
        "grunt-contrib-sass": "~0.2.2",
        "grunt-contrib-copy": "~0.4.0",
        "grunt-contrib-concat": "~0.1.3",
        "grunt-contrib-uglify": "~0.1.2"
    }
}

Verbose on command > grunt sass-- --verbose

Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK 
Initializing config...OK 

Registering "grunt-contrib-sass" local Npm module tasks. 
Reading c:\workspaces\DEV\Grunt\node_modules\grunt-contrib-sass\package.json...OK 
Parsing c:\workspaces\DEV\Grunt\node_modules\grunt-contrib-sass\package.json...OK 
Loading "sass.js" tasks...OK 
- sass 
  Loading "Gruntfile.js" tasks...OK 
- default, sass-- 

Running tasks: sass-- 

Running "sass--" task

Running "sass" task

Running "sass:dist" (sass) task
Verifying property sass.dist exists in config...OK 
Files: src/scss/illicoweb.scss -> build/css/illicoweb.css 
Options: style="expanded", trace 
Reading src/scss/illicoweb.scss...OK 
Writing build/css/illicoweb.css...OK 
c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:163:in `initialize': No such file or directory - build/css/illicoweb.css (Errno::ENOENT)
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:163:in`open'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:163:in `open_file'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:111:in`process_result'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:308:in `process_result'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:41:in`parse'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:21:in `parse!'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/bin/sass:9:in`<top (required)>'
        from c:/Ruby193/bin/sass:23:in `load'
        from c:/Ruby193/bin/sass:23:in`<main>'
Warning: c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:163:in `initialize': No such file or directory - build/css/illicoweb.css (Errno::ENOENT) 
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:163:in`open' 
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:163:in `open_file' 
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:111:in`process_result' 
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:308:in `process_result' 
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:41:in`parse' 
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/lib/sass/exec.rb:21:in `parse!' 
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.7/bin/sass:9:in`<top (required)>' 
        from c:/Ruby193/bin/sass:23:in `load' 
        from c:/Ruby193/bin/sass:23:in`<main>' Use --force to continue. 

Your help is greatly appreciated

Thank you
Niusaul

**Comment by tinny77** [comment]
Thanks niusaul. I tried **everything**, cleaned cache, reinstalled ruby, npm, sass... And it was just the Autorun I added to regedit. Can't believe it. Thanks!
