### ISSUE TITLE
Socket is closed error

### ISSUE THREAD

**Issue by milesj** [gruntjs/grunt-contrib-sass#33]
I'm trying to setup SASS in my grunt project but I keep receiving the following error when running a target:

```
Running "sass:build" (sass) task
Warning: This socket is closed. Use --force to continue.

Aborted due to warnings.
```

All my other tasks work fine: uglify, concat, compress, jslint, etc. I'm assuming this is more of a Ruby error and not Sass, but no amount of Googling has solved my problem.

Here is the gruntfile: https://github.com/titon/Toolkit/blob/master/Gruntfile.js

I'm using Window 7 + Cygwin + command prompt when running grunt. I know sass works outside of grunt because I use scout and the command line daily.

Any help would be appreciated.

**Comment by qzhu** [comment]
There is a actually workaround ! Running `sass` in a window command prompt launched after running `cygstart cmd` in cygwin terminal, that will setup windows PATH environment variable to include cygwin related directories.

When  running `sass` alone, still got a `Command not found` error, the *key* to circumvent that is a windows batch wrapper `sass.cmd` with following code:

```bat
@echo off
set DIRNAME=%~dp0
ruby %DIRNAME%\sass %*
```
 
P.S. put that `sass.cmd` under the same location with `sass` ruby script. (that is also under PATH, mine's ~/bin/)
