### ISSUE TITLE
compile many sass files ?

### ISSUE THREAD

**Issue by tamamadesu** [gruntjs/grunt-contrib-sass#55]
when i  use like this : 

'files:{
          './public/css/style-min.css':['./develop/{,_/,_/_/}_.{scss,sass}']
        }'

it seem always  compile the  first sass file, but i want it  compile the all sass files, how should i do  ?,,

**Comment by landed1** [comment]
I just thought I would post a helper note here for others that tried to import css files and found the sass compiler just writes the import line the same (no change) when I wanted it to take the content of that file and incorporate it into my output.

@import "myfile.css" 
vs
@import "myfile.scss" 

the first way the compiler leaves alone the second way it does what I wanted and takes the content scss and compiles it into the destination file.

**Comment by tbremer** [comment]
You should drop the file extension on import calls of s[a|c]ss files.

**Comment by landed1** [comment]
oh cool didn't know that was possible -> I saw what you did there with s[a|c]ss :)

**Comment by pbouzakis** [comment]
Not sure why concat is not support, import doesn't support glob patterns right?
