### ISSUE TITLE
Ability to use Sass Globbing as an option

### ISSUE THREAD

**Issue by benfrain** [gruntjs/grunt-contrib-sass#57]
Would be great if alongside source maps there was the ability to support [Sass Globbing](https://github.com/chriseppstein/sass-globbing) (really handy for doing batch imports of low level library files where specificity is not an issue).

**Comment by EvanAgee** [comment]
Thanks for the info, but even after installing the gem for sass-globbing using 'require: 'sass-globbing'' but I'm getting this error when running grunt watch.

    LoadError: cannot load such file -- sass-globbing

**Comment by dd-kunai** [comment]
@sindresorhus I'm experiencing the same issue as @EvanAgee. Here is my code:
```
sass: {
            build: {
                files: [{
                    expand: true,
                    cwd: 'src/sass',
                    src: 'main.scss',
                    dest: '<%= build_dir %>/assets/',
                    ext: '.css'
                }],
                options: {
                    style: 'expanded',
                    noCache: true,
                    require: 'sass_globbing'
                }
            }
        },

        sass_globbing: {
            your_target: {
                files: {
                    'src/_app-files.scss': 'src/app/**/*.scss',
                    'src/_shared-components.scss': 'src/sass/shared-components/**/*.scss',
                    'src/_mixins.scss': 'src/sass/mixins/**/*.scss',
                    'src/_functions.scss': 'src/sass/functions/**/*.scss'
                },
                options: {
                    useSingleQuotes: false
                }
            }
        }
```
Could you please give me some heads up please? I would really appreciate it :smile:

**Comment by dd-kunai** [comment]
Nevermind, solved the issue by fixing the routes where save the mapped files and adding `sass_globbing` to `grunt.registerTask('build', [])`.

Thanks anyway :+1:

**Comment by josephbergdoll** [comment]
@DD-UX how did you end up getting this working? This is with the Sass-Globbing gem, correct?
