### ISSUE TITLE
On Windows, Ruby has to be manually added to PATH

### ISSUE THREAD

**Issue by simevidas** [gruntjs/grunt-contrib-sass#61]
I've installed [RubyInstaller for Windows](http://rubyinstaller.org/) (the "Ruby 2.0.0-p247 (x64)" version) and then ran `gem install sass`. After that, I've ran your Grunt plugin and got this message:

> Warning: You need to have Ruby and Sass installed and in your PATH for this task to work.

I've checked the value of PATH (`echo %PATH%`) and, indeed, Ruby was not in there. I had to **add it manually**:

```
set PATH=C:\Ruby200-x64\bin;%PATH%
```

Now, your Grunt plugin works for me.

So, since it appears that, on Windows, one has to manually add Ruby to PATH in order for your Grunt plugin to work, consider adding a note in your README file with information how to do this.

**Comment by josersjq** [comment]
Thanks!!!

**Comment by TransparentD8** [comment]
Thanks !!!

**Comment by jSilverize** [comment]
Very helpful!
Thank you

**Comment by krunalsha** [comment]
Thanks simevidas.

**Comment by sumantaparida** [comment]
not working?

**Comment by pawell67** [comment]
Very helpful!
