### ISSUE TITLE
Random "Warning: Errno::ENOENT: No such file or directory"

### ISSUE THREAD

**Issue by MoOx** [gruntjs/grunt-contrib-sass#63]
I'm getting a lot of random issues like 1/3 of the time I save a file (using a watch config). Sometimes happen during first build so not related to watch I think.

Using v0.4.1.

``` bash
Warning: Errno::ENOENT: No such file or directory - ./.sass-cache/a2bcc5caa8ce244248ac392bcdf3cb6fa5e06e10/_listing.scssc
      Use --trace for backtrace. Use --force to continue.
```

Any idea why ?

**Comment by svenboogaart** [comment]
Same problem here it was a too long filename. it sucks now i had to completely adjust my workflow folders

**Comment by themestechnology** [comment]
There might be something broken in your Grunt.js file or a file/folder missing

For me I had not done bower install

**Comment by wouterNL** [comment]
I fixed it, I didn't had root access to the .sass-cache folder. When I switched to my root account I had no problems at all, no more errors.

**Comment by yuriregis** [comment]
Corriga apagando no config.rb a linha 1: require 'compass/import-once/activate' 
Fix erasing the config.rb line 1: require 'compass/import-once/activate'  delete

**Comment by RajRanjan** [comment]
I got the same errror
Errno::ENOENT: No such file or directory @ rb_sysopen - undefined
  Use --trace for backtrace.
Warning: Exited with error code 1 Use --force to continue.

Aborted due to warnings.


i researched and found that the file location for sass was wrong.
I corrected the file location and it compiled file.

**Comment by gregdegruy** [comment]
I got the same errror
Errno::ENOENT: No such file or directory @ rb_sysopen - undefined
Use --trace for backtrace.
Warning: Exited with error code 1 Use --force to continue.

Running "grunt-contrib-sass": "^0.9.2",

**Comment by nhhockeyplayer** [comment]
uninstall grunt-contrib-sass
uninstall grunt-contrib-uglify

these were conflicting with my gulp-sass and gulp-uglify

**Comment by StagnantIce** [comment]
Install:

Ruby 2.2
grunt-contrib-sass to 0.4.x

and this fix my problem

**Comment by agreif84** [comment]
Upgrading Ruby/SASS did not help, but downgrading to grunt-contrib-sass v0.8.1 did it for me. Error seemed only to occur on windows-systems. Maybe that might help anyone else.

**Comment by Mujaddadi** [comment]
I am also getting this error.

**Comment by joncodo** [comment]
@agreif84 You are totally right here! This is a real error in v 1.0.0

**Comment by joncodo** [comment]
This should be re-opened

**Comment by viniciuspires** [comment]
I also think this should be reopened, I'm having the same problem in Linux, with the pointed versions that should solve the problem. Here's my env:

```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.5 (Santiago)
```

```
$ which ruby
/usr/local/bin/ruby
$ /usr/local/bin/ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

```
$ which sass
/usr/local/bin/sass
$ /usr/local/bin/sass -v
Sass 3.4.22 (Selective Steve)
```

```
$ head ./node_modules/grunt-contrib-sass/package.json 
{
  "name": "grunt-contrib-sass",
  "description": "Compile Sass to CSS",
  "version": "0.8.1",
  "homepage": "https://github.com/gruntjs/grunt-contrib-sass",
  "author": {
    "name": "Grunt Team",
    "url": "http://gruntjs.com/"
  },
  "repository": {
```

I'm running a grunt task through jenkins, and it's always failing with the same issue below and no more other info:

```
+ grunt war-dist
[4mRunning "clean:0" (clean) task[24m
[32m>> [39m0 paths cleaned.

[4mRunning "jshint:files" (jshint) task[24m
[32m>> [39m245 files lint free.

[4mRunning "sass:dist" (sass) task[24m
[33mWarning: spawn sass ENOENT Use --force to continue.[39m

[31mAborted due to warnings.[39m
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by viniciuspires** [comment]
I was able to solve the problem, Jenkins was somehow overriding the $PATH variable, and losing the `/usr/local/bin/` path. I did a `export PATH=$PATH:/usr/local/bin` and it was able to locate `ruby` and `sass` and it worked just fine.

**Comment by elCanarioVidal** [comment]
Hi guys, for a simple mortal, how can I solve this problem!!!!!???

**Comment by joncodo** [comment]
@elCanarioVidal can you tell me which version you are using?
