### ISSUE TITLE
Adding gems dependencies via `require`

### ISSUE THREAD

**Issue by zslabs** [gruntjs/grunt-contrib-sass#67]
Hi all,
Here is the SASS portion of my Gruntfile:

```
sass: {
    dist: {
        options: {
            style: 'compressed',
            require: ['zurb-foundation', 'bourbon']
        },
        files: {
            'dist/css/styles.css': 'src/sass/app.scss'
        }
    }
},
```

What I'm trying to do is require both the Foundation framework and Bourbon mixin library. When I try to compile, it says the path to read in the Foundation files is not readable (or supplied) even though they are installed on my system (I've used Codekit in the past with Compass, but want to move away from it). Is there something specific I'd have to do add to pull-in these gems? Thanks!

**Comment by allejo** [comment]
@Pushplaybang I don't believe this is an issue with Grunt but instead with SASS or the plug-in. The command being executed by this Grunt plug-in is correct, it's just the plug-in or SASS that's not handling it correctly.

**Comment by Pushplaybang** [comment]
nice, thanks Allejo!
