### ISSUE TITLE
[Windows 7] "The system cannot find the path specified."

### ISSUE THREAD

**Issue by jelmerdemaat** [gruntjs/grunt-contrib-sass#77]
On Windows 7, Ruby 2.0.0 + DevKit installed, package modules installed via `npm install [name] --save-dev`, I keep getting the following error:

```
Running "sass:dist" (sass) task
The system cannot find the path specified.
Warning:  Use --force to continue.

Aborted due to warnings.
```

My gruntfile looks as follows:

``` javascript
module.exports = function(grunt) {

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        sass: {
            dist: {
                options: {
                    style: 'compact',
                    compass: true
                },
                files: {
                    'style.css': 'sass/style.scss'
                }
            }
        },
        watch: {
            files: ['sass/**/*.scss','sass/**/*.sass'],
            tasks: ['default']
        }
    });

    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.loadNpmTasks('grunt-contrib-watch');

    grunt.registerTask('default', ['sass']);

};

```

`style.css` gets compiled to the root. It does work (although it seems to compile twice) but I keep getting the error. Even with clean projects I start I get this message. Am I declaring something wrong?

**Comment by SoniaGarmar** [comment]
I know that's an old post, but just i n case this can help someone. It might seem a little silly but... Do you have sass installed? 
`gem install sass` in case you don't

**Comment by vwswebmaster** [comment]
Thanks SoniaGarmar, I had sass installed, thought I reinstalled it but somehow it wasn't. Your post did the trick!

**Comment by SoniaGarmar** [comment]
@vwswebmaster  Glad to help!

**Comment by raphievila** [comment]
It is funny @SoniaGarmar how something that obvious can be the culprit. Because I have Sass installed on my main environment I forgot to install it on my new laptop. Unconsciously I assumed was already installed, not realizing that was not... duh! Appreciate your comment on an old thread, it is always good to have new insights in old questions and problems.
